// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwpburocxzmcffcjmulp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3cGJ1cm9jeHptY2ZmY2ptdWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMDIzNzksImV4cCI6MjA2MTg3ODM3OX0.8lQf4xBKHmSn7tUWtl35oTwA5FumH9xuUquKiWskSqk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);